#include <iostream>
using namespace std;

///using ///single line comment
//dhdhjhjf


/*
dkljhdfkhfdkhfdk  ///mutiple line comment
oskjdsdhjdfxkj
kjddsjdjd */
int main(){
   /* int x; ///defining a variable declaration ///have a garbage value
    x=10;   ///assignment

    int y=10;  ///initailisation  ///defining and giving value at the same time */

    int x;
    cin>>x; ///input you cin

    cout << x << endl;

    cout << "my name is mohit" << endl;




}
