#include <iostream>
using namespace std;


int main(){
    int x;
    cin>>x;

    //if(x==0)
   // cout << "mohit";  ///only this is a part of if

   // cout << "rohit";
   /* if(x==0){
        cout << "Sunday" << endl;  ///endl- go to new line
    }
    else if(x==1)
        cout << "Monday" << endl;

    else if(x==2 || x==1){
        cout << "tuesday" << endl;
    }
    else{
        cout << "some other day" << endl;
    }
 */
    ///mutiple if are independent

    ///switch
    switch(x){

    case 1:
        cout << "Mohit";
        break;

    case 3:
        cout << "skjkjdf";
        break;

           default:
        cout << "Rohit";



     ///break will you take here

}
}
