#include <iostream>
using namespace std;


int main(){
       int count =1;  ///initalisation

      /* while(count){ ///count!=0  ///true value is any value that is not zero
          ///do repeated times
          cout << count << endl;

          ///increment
          count =count +1;
       } */
     /*  do{
           ///repeated task
           cout << "hello" << " " << "world";

           count++; ///increment
       }
       while(count<=0);   ///condition is checked at last */

}


